---
title: "Exploración plantas extintas"
author: "Jorn Bethke"
date: "11/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message =  FALSE)

library(tidyverse)
library(kableExtra)
```

## Introducción

### de donde vienen los datos

Estos datos sobre plantas extintas son datos de la **IUCN**, y fueron obtenidos del [siguiente repositorio](https://github.com/rfordatascience/tidytuesday) de Github.

```{r}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')
```

##Datos de Sudamérica 

Del total de especies de plantas extintas que hay en la base de datos, existen **`r plants %>% dplyr::filter(continent == "South America") %>% nrow()`** especies de Sudamérica.
